sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

script:
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - cmake -DCMAKE_BUILD_TYPE=RelCheck .
  - make
  - make test
